### ISSUE TITLE
Coverage is displayed wrong

### ISSUE THREAD

**Issue by qznc** [dlang-community/d-money#1]
The button currently shows 99% test coverage. However, the money.d file is covered 100%. It is some /tmp/dub_test_root_something.d file which is uncovered and somehow included for the statistics.

Maybe https://github.com/ColdenCullen/doveralls is outdated? Maybe https://codecov.io is an alternative?

**Comment by qznc** [comment]
@wilzbach any opinion how to report coverage well?

dlang-community/discussions#15 discusses this issue as well.

**Comment by mw66** [comment]
Also I saw the version is bump to 3.0.0

https://github.com/dlang-community/d-money/releases/tag/v3.0.0

but dub still haven't picked it up?

https://code.dlang.org/packages/money

2.5.0 released 7 days ago

**Comment by mw66** [comment]
$ dub upgrade

Unresolvable dependencies to package money:
  ats ~master depends on money ~>3.0.0

**Comment by mw66** [comment]
Also even on github, the latest version is not showing:

https://github.com/dlang-community/d-money

it's showing dub v2.5.0

**Comment by qznc** [comment]
There seems to be a bigger issue with the registry: https://github.com/dlang/dub-registry/issues/462

**Comment by mw66** [comment]
Maybe it's because of this `d-money` repo's setup issue?

I just saw on https://code.dlang.org/

The other package I reviewed showed up:

fixedpoint 0.1.1
Decimal fixed point type
updated 17 minutes ago

But this package's update is not picked up.

**Comment by wilzbach** [comment]
> @wilzbach any opinion how to report coverage well?
> 
> [dlang-community/discussions#15](https://github.com/dlang-community/discussions/issues/15) discusses this issue as well.

I made pretty good experience with CodeCov and we use it for the main DMD/Druntime/Phobos repositories.
On Travis all you need to do is add:

```yaml
after_success:
 - bash <(curl -s https://codecov.io/bash)
```

IIRC `dub` automatically adds coverage info on CI, but if not you can do e.g. `dub test --coverage` or  `DFLAGS="-cov" dub`.

Codecov supports a few other options like e.g. excluding unwanted files from the report, which might also help to solve your problem.
We use this feature at e.g. DMD: https://github.com/dlang/dmd/blob/master/.codecov.yml

**Comment by qznc** [comment]
Switched to codecov and issue is fixed.

I also added a grep command to the CI, so it fails now if coverage decreases.
